# Project Name
TARGET = Poly3

# Sources
CPP_SOURCES = Poly3.cpp subs.cpp voice.cpp voice_square.cpp myOscillator.cpp

# Library Locations
LIBDAISY_DIR = /home/quentinlister/DaisyExamples/libDaisy/
DAISYSP_DIR = /home/quentinlister/DaisyExamples/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

